import {
  useEffect,
  useState
} from "react";

import axios from "axios";

import {
  useNavigate,
  useParams
} from "react-router-dom";

function Analysis() {

  const navigate = useNavigate();

  const { roomId } = useParams();

  const [messages, setMessages] =
    useState([]);

  const [analysis, setAnalysis] =
    useState(null);

  /* LOAD MESSAGES */

  useEffect(() => {

    const fetchMessages = async () => {

      try {

        const res =
          await axios.get(
            `http://localhost:5000/messages/${roomId}`
          );

        setMessages(res.data);

      }

      catch(err) {

        console.log(err);

      }

    };

    fetchMessages();

  }, [roomId]);

  /* ANALYZE */

  useEffect(() => {

    if(messages.length === 0) return;

    const totalMessages =
      messages.length;

    const emojiCount =
      messages.filter((msg) =>

        /❤️|💖|😭|✨|🥹|😍|😘|💕|💌/.test(
          msg.text
        )

      ).length;

    const shortReplies =
      messages.filter((msg) =>

        msg.text.length <= 3

      ).length;

    const longMessages =
      messages.filter((msg) =>

        msg.text.length > 25

      ).length;

    const playfulMessages =
      messages.filter((msg) =>

        /haha|lol|lmao|😭|😂|hehe/i.test(
          msg.text
        )

      ).length;

    /* SCORES */

    let loveScore = 60;

    loveScore +=
      emojiCount * 2;

    loveScore +=
      playfulMessages * 3;

    loveScore +=
      longMessages * 2;

    loveScore -=
      shortReplies * 2;

    if(loveScore > 98)
      loveScore = 98;

    if(loveScore < 40)
      loveScore = 40;

    /* DRY RISK */

    let dryRisk =
      "extremely low";

    if(shortReplies > 8)
      dryRisk = "medium";

    if(shortReplies > 15)
      dryRisk = "high";

    /* ENERGY */

    let energy =
      "Cozy Energy";

    if(playfulMessages > 5)
      energy =
        "Golden Retriever Energy";

    /* OBSERVATIONS */

    const observations = [];

    if(playfulMessages > 4){

      observations.push(
        "💖 You both mirror each other's humor a lot."
      );

    }

    if(emojiCount > 5){

      observations.push(
        "✨ Emotional expression is very visible in conversations."
      );

    }

    if(longMessages > 3){

      observations.push(
        "☁ One or both partners enjoy deep conversations."
      );

    }

    if(shortReplies > 8){

      observations.push(
        "🌧 Dry texting moments were detected sometimes."
      );

    }

    if(observations.length === 0){

      observations.push(
        "💌 Your conversations feel balanced and comfortable."
      );

    }

    setAnalysis({

      loveScore,

      dryRisk,

      energy,

      totalMessages,

      observations

    });

  }, [messages]);

  if(!analysis){

    return (

      <div className="analysis-card">

        <h1>
          analyzing chemistry... ✨
        </h1>

      </div>

    );

  }

  return (

    <div className="analysis-card">

      {/* TOP */}

      <div className="analysis-top">

        <h1>
          your relationship wrapped ♡
        </h1>

        <p>
          generated by CupidOS ✨
        </p>

      </div>

      {/* SCORE */}

      <div className="love-score">

        <h2>
          {analysis.loveScore}%
        </h2>

        <span>
          love sync ♡
        </span>

      </div>

      {/* GRID */}

      <div className="analysis-grid">

        <div className="analysis-box yellow">

          <h3>
            ☀ {analysis.energy}
          </h3>

          <p>
            emotionally warm and active
          </p>

        </div>

        <div className="analysis-box pink">

          <h3>
            💌 Message Count
          </h3>

          <p>
            {analysis.totalMessages}
            total messages exchanged
          </p>

        </div>

        <div className="analysis-box white">

          <h3>
            ☁ Dry Texting Risk
          </h3>

          <p>
            {analysis.dryRisk}
            detected risk
          </p>

        </div>

        <div className="analysis-box lavender">

          <h3>
            ✨ Chemistry Status
          </h3>

          <p>
            strong emotional interaction
          </p>

        </div>

      </div>

      {/* NOTES */}

      <div className="ai-notes">

        <h2>
          AI observations ✨
        </h2>

        {analysis.observations.map(
          (note, index) => (

            <div
              key={index}
              className="note"
            >

              {note}

            </div>

          )
        )}

      </div>

      <button
        className="primary-btn"
        onClick={() => navigate("/")}
      >

        back home ♡

      </button>

    </div>

  );

}

export default Analysis;